### ISSUE TITLE
Неправильно указана версия node 14 в зависимостях package.json.

### ISSUE THREAD

**Issue by Lyumih** [hyoo-ru/mam#23]
https://github.com/hyoo-ru/mam/blob/master/package.json#L21

Указана, "node": ">=14.0.0" , но при выполнении команды nvm install , получаем ошибку TypeError: path.replaceAll is not a function. Это связанно с тем, что данная функция появилась только в 15 ноде. Нужно или изменить требование на ноду 15, или добавить полифил для 14 версии.

![image](https://user-images.githubusercontent.com/32732179/208511470-92e67361-a0ee-48f8-b84c-1e8d15eb4bca.png)

**Comment by nin-jin** [comment]
Поднял до 15.
